version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      XDEBUG_CONFIG: idekey=PHPSTORM
  wordpress:
    depends_on:
      - db
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./wp-avorg-plugin:/var/www/html/wp-content/plugins/wp-avorg-plugin
      - ./pwa:/var/www/html/wp-content/plugins/pwa
      - ./transfer:/var/www/html/transfer
      - ./logs:/logs
      - ./transfer/php.ini:/usr/local/etc/php/php.ini
      - ./transfer/error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
volumes:
  dbdata:
